const groups = [
    { id: 1, group: "9ИС-120" },
    { id: 2, group: "11КС-250" },
    { id: 3, group: "9ИС-430" },
];

const students = [
    { "id": 1, "group_id": 1, "student": "Иванов Иван" },
    { "id": 2, "group_id": 1, "student": "Максимов Максим" },
    { "id": 3, "group_id": 1, "student": "Андреев Андрей" },
    { "id": 4, "group_id": 2, "student": "Миронова Мария" },
    { "id": 5, "group_id": 2, "student": "Алексеев Алексей" },
    { "id": 6, "group_id": 3, "student": "Никитин Никита" },
    { "id": 7, "group_id": 3, "student": "Иванов Иван" },
    { "id": 8, "group_id": 3, "student": "Петров Петр" },
    { "id": 9, "group_id": 3, "student": "Сидоров Сидор" },
    { "id": 10, "group_id": 3, "student": "Семенов Семен" },
    { "id": 11, "group_id": 3, "student": "Васильев Василий" },
    { "id": 12, "group_id": 3, "student": "Александров Александр" },
    { "id": 13, "group_id": 3, "student": "Николаев Николай" },
    { "id": 14, "group_id": 3, "student": "Павлов Павел" },
    { "id": 15, "group_id": 3, "student": "Сергеев Сергей" },
    { "id": 16, "group_id": 3, "student": "Андреев Андрей" },
    { "id": 17, "group_id": 3, "student": "Дмитриев Дмитрий" },
    { "id": 18, "group_id": 3, "student": "Егоров Егор" },
    { "id": 19, "group_id": 3, "student": "Борисов Борис" },
    { "id": 20, "group_id": 3, "student": "Волков Волк" },
    { "id": 21, "group_id": 3, "student": "Зайцев Зайц" },
    { "id": 22, "group_id": 3, "student": "Козлов Козел" },
    { "id": 23, "group_id": 3, "student": "Левин Лев" },
    { "id": 24, "group_id": 3, "student": "Константинов Константин" },
    { "id": 25, "group_id": 3, "student": "Орлов Орлов" },
    { "id": 26, "group_id": 3, "student": "Романов Роман" },
    { "id": 27, "group_id": 3, "student": "Королев Королев" },
    { "id": 28, "group_id": 3, "student": "Носов Нос" },
    { "id": 29, "group_id": 3, "student": "Горбачев Горбач" },
    { "id": 30, "group_id": 3, "student": "Чернышов Черныш" },
];

const subjects = [
    { id: 1, subject: "Алгебра", teacher_id: 13 },
    { id: 2, subject: "Литература", teacher_id: 27 },
    { id: 3, subject: "История", teacher_id: 42 },
    { id: 4, subject: "Биология", teacher_id: 18 },
    { id: 5, subject: "Химия", teacher_id: 36 },
    { id: 6, subject: "Геометрия", teacher_id: 2 },
    { id: 7, subject: "Английский язык", teacher_id: 48 },
    { id: 8, subject: "География", teacher_id: 11 },
    { id: 9, subject: "Обществознание", teacher_id: 45 },
    { id: 10, subject: "Физкультура", teacher_id: 31 },
    { id: 11, subject: "Физика", teacher_id: 22 },
    { id: 12, subject: "Информатика", teacher_id: 41 },
    { id: 13, subject: "Русский язык", teacher_id: 50 },
    { id: 14, subject: "Трудовое обучение", teacher_id: 15 },
    { id: 15, subject: "Музыка", teacher_id: 29 },
    { id: 16, subject: "Экология", teacher_id: 33 },
    { id: 17, subject: "Экономика", teacher_id: 47 },
    { id: 18, subject: "Психология", teacher_id: 8 },
    { id: 19, subject: "Технология", teacher_id: 21 },
    { id: 20, subject: "Искусство", teacher_id: 39 },
    { id: 21, subject: "Начертательная геометрия", teacher_id: 16 },
    { id: 22, subject: "Философия", teacher_id: 44 },
    { id: 23, subject: "Право", teacher_id: 37 },
    { id: 24, subject: "Основы безопасности жизнедеятельности", teacher_id: 40 },
    { id: 25, subject: "Французский язык", teacher_id: 24 },
    { id: 26, subject: "Немецкий язык", teacher_id: 12 },
    { id: 27, subject: "Испанский язык", teacher_id: 35 },
    { id: 28, subject: "Китайский язык", teacher_id: 46 },
    { id: 29, subject: "Итальянский язык", teacher_id: 19 },
    { id: 30, subject: "Теория вероятностей", teacher_id: 30 },
    { id: 31, subject: "Математический анализ", teacher_id: 38 },
    { id: 32, subject: "Программирование", teacher_id: 43 },
    { id: 33, subject: "Робототехника", teacher_id: 7 },
    { id: 34, subject: "Электротехника", teacher_id: 26 },
    { id: 35, subject: "Автоматизация процессов", teacher_id: 34 },
    { id: 36, subject: "Теплотехника", teacher_id: 49 },
    { id: 37, subject: "Гидравлика", teacher_id: 14 },
    { id: 38, subject: "Строительное дело", teacher_id: 5 },
    { id: 39, subject: "Металлургия", teacher_id: 32 },
    { id: 40, subject: "Транспортные системы", teacher_id: 20 },
    { id: 41, subject: "Проектирование зданий", teacher_id: 17 },
    { id: 42, subject: "Архитектура", teacher_id: 6 },
    { id: 43, subject: "Менеджмент", teacher_id: 23 },
    { id: 44, subject: "Маркетинг", teacher_id: 25 },
    { id: 45, subject: "Бухгалтерский учёт", teacher_id: 4 },
    { id: 46, subject: "Управление персоналом", teacher_id: 3 },
    { id: 47, subject: "Международные отношения", teacher_id: 9 },
    { id: 48, subject: "Политология", teacher_id: 10 },
    { id: 49, subject: "Реклама и связи с общественностью", teacher_id: 28 },
    { id: 50, subject: "Документационное обеспечение управления", teacher_id: 1 },
    { id: 51, subject: "Медицина", teacher_id: 33 },
    { id: 52, subject: "Спортивная подготовка", teacher_id: 40 },
    { id: 53, subject: "Педагогика", teacher_id: 2 },
    { id: 54, subject: "Информационные технологии", teacher_id: 18 },
    { id: 55, subject: "Косметология", teacher_id: 11 },
    { id: 56, subject: "Логистика", teacher_id: 36 },
    { id: 57, subject: "Фотография", teacher_id: 29 },
    { id: 58, subject: "Видеоискусство", teacher_id: 35 },
    { id: 59, subject: "Астрономия", teacher_id: 44 },
    { id: 60, subject: "Этнография", teacher_id: 26 },
    { id: 61, subject: "Культурология", teacher_id: 41 },
    { id: 62, subject: "Художественное творчество", teacher_id: 47 },
    { id: 63, subject: "Компьютерная графика", teacher_id: 12 },
    { id: 64, subject: "Режиссура", teacher_id: 19 },
    { id: 65, subject: "Сценическое искусство", teacher_id: 34 },
    { id: 66, subject: "Библиотечное дело", teacher_id: 24 },
    { id: 67, subject: "Музыкальное исполнительство", teacher_id: 43 },
    { id: 68, subject: "Хореография", teacher_id: 46 },
    { id: 69, subject: "Основы электроники", teacher_id: 14 },
    { id: 70, subject: "Машиноведение", teacher_id: 32 },
    { id: 71, subject: "Основы электротехники", teacher_id: 45 },
    { id: 72, subject: "Основы автоматики", teacher_id: 38 },
    { id: 73, subject: "Основы механики", teacher_id: 31 },
    { id: 74, subject: "Организация производства", teacher_id: 17 },
    { id: 75, subject: "Охрана труда", teacher_id: 30 },
    { id: 76, subject: "Безопасность жизнедеятельности", teacher_id: 23 },
    { id: 77, subject: "Экологическое право", teacher_id: 49 },
    { id: 78, subject: "Генетика", teacher_id: 42 },
    { id: 79, subject: "Микробиология", teacher_id: 20 },
    { id: 80, subject: "Иммунология", teacher_id: 16 },
    { id: 81, subject: "Анатомия", teacher_id: 37 },
    { id: 82, subject: "Физиология", teacher_id: 25 },
    { id: 83, subject: "Патологическая анатомия", teacher_id: 39 },
    { id: 84, subject: "Судебная медицина", teacher_id: 10 },
    { id: 85, subject: "Фармацевтика", teacher_id: 28 },
    { id: 86, subject: "Валеология", teacher_id: 48 },
    { id: 87, subject: "Фитотерапия", teacher_id: 3 },
    { id: 88, subject: "Акупунктура", teacher_id: 40 },
    { id: 89, subject: "Радиобиология", teacher_id: 9 },
    { id: 90, subject: "Фармакология", teacher_id: 21 },
    { id: 91, subject: "Клиническая психология", teacher_id: 6 },
    { id: 92, subject: "Социальная работа", teacher_id: 46 },
    { id: 93, subject: "Филантропия", teacher_id: 15 },
    { id: 94, subject: "Философские проблемы науки", teacher_id: 33 },
    { id: 95, subject: "Историко-культурное наследие", teacher_id: 22 },
    { id: 96, subject: "Современные технологии строительства", teacher_id: 12 },
    { id: 97, subject: "Конструирование машин", teacher_id: 34 },
    { id: 98, subject: "Энергосбережение", teacher_id: 24 },
    { id: 99, subject: "Автомобильные дороги", teacher_id: 43 },
    { id: 100, subject: "Водоснабжение и водоотведение", teacher_id: 4 },
    { id: 101, subject: "Газоснабжение", teacher_id: 27 },
    { id: 102, subject: "Теплоснабжение", teacher_id: 36 },
    { id: 103, subject: "Экологический мониторинг", teacher_id: 47 },
    { id: 104, subject: "Мониторинг природных ресурсов", teacher_id: 35 },
    { id: 105, subject: "Картография", teacher_id: 26 },
    { id: 106, subject: "Гидрология", teacher_id: 11 },
    { id: 107, subject: "Почвоведения", teacher_id: 19 },
    { id: 108, subject: "Биогеоценология", teacher_id: 18 },
    { id: 109, subject: "Защита растений", teacher_id: 41 },
    { id: 110, subject: "Агрохимия", teacher_id: 30 },
    { id: 111, subject: "Сельскохозяйственная техника", teacher_id: 49 },
    { id: 112, subject: "Животноводство", teacher_id: 42 },
    { id: 113, subject: "Пчеловодство", teacher_id: 32 },
    { id: 114, subject: "Рыболовство", teacher_id: 20 },
    { id: 115, subject: "Туризм", teacher_id: 16 },
    { id: 116, subject: "Гостиничный бизнес", teacher_id: 37 },
    { id: 117, subject: "Курортное дело", teacher_id: 25 },
    { id: 118, subject: "Питание туристов", teacher_id: 39 },
    { id: 119, subject: "Санитария и гигиена", teacher_id: 10 },
    { id: 120, subject: "Диагностика заболеваний", teacher_id: 28 },
    { id: 121, subject: "Терапия", teacher_id: 48 },
    { id: 122, subject: "Ортопедическая стоматология", teacher_id: 3 },
    { id: 123, subject: "Протезирование зубов", teacher_id: 40 },
    { id: 124, subject: "Неврология", teacher_id: 9 },
    { id: 125, subject: "Хирургия", teacher_id: 21 },
    { id: 126, subject: "Операционная техника", teacher_id: 6 },
    { id: 127, subject: "Инфекционные болезни", teacher_id: 46 },
    { id: 128, subject: "Эпидемиология", teacher_id: 15 },
    { id: 129, subject: "Гинекология", teacher_id: 33 },
    { id: 130, subject: "Педиатрия", teacher_id: 22 },
    { id: 131, subject: "Лабораторная диагностика", teacher_id: 12 },
    { id: 132, subject: "Реабилитация пациентов", teacher_id: 34 },
    { id: 133, subject: "Интегративная медицина", teacher_id: 24 },
    { id: 134, subject: "Психиатрия", teacher_id: 43 },
    { id: 135, subject: "Кардиология", teacher_id: 4 },
    { id: 136, subject: "Гастроэнтерология", teacher_id: 27 },
    { id: 137, subject: "Нефрология", teacher_id: 36 },
    { id: 138, subject: "Отоларингология", teacher_id: 47 },
    { id: 139, subject: "Онкология", teacher_id: 35 },
    { id: 140, subject: "Радиология", teacher_id: 26 },
    { id: 141, subject: "Радиотерапия", teacher_id: 11 },
    { id: 142, subject: "Трансфузиология", teacher_id: 19 },
    { id: 143, subject: "Ангиология", teacher_id: 18 },
    { id: 144, subject: "Пластическая хирургия", teacher_id: 41 },
    { id: 145, subject: "Флебология", teacher_id: 30 },
    { id: 146, subject: "Эндокринология", teacher_id: 49 },
    { id: 147, subject: "Проктология", teacher_id: 42 },
    { id: 148, subject: "Урология", teacher_id: 32 },
    { id: 149, subject: "Андрология", teacher_id: 20 },
    { id: 150, subject: "Диетология", teacher_id: 16 },
    { id: 151, subject: "Иммунизация населения", teacher_id: 37 },
    { id: 152, subject: "Профессиональные заболевания", teacher_id: 25 },
    { id: 153, subject: "Социальная политика", teacher_id: 39 },
    { id: 154, subject: "Политэкономия", teacher_id: 10 },
    { id: 155, subject: "Эконометрика", teacher_id: 28 },
    { id: 156, subject: "Статистика", teacher_id: 48 },
    { id: 157, subject: "Анализ хозяйственной деятельности", teacher_id: 3 },
    { id: 158, subject: "Государственный бюджет", teacher_id: 40 },
    { id: 159, subject: "Банковская деятельность", teacher_id: 9 },
    { id: 160, subject: "Страхование", teacher_id: 21 },
    { id: 161, subject: "Оценочная деятельность", teacher_id: 6 },
    { id: 162, subject: "Финансовое управление предприятием", teacher_id: 46 },
    { id: 163, subject: "Предпринимательство", teacher_id: 15 },
    { id: 164, subject: "Инвестиции", teacher_id: 33 },
    { id: 165, subject: "Биржевая торговля", teacher_id: 22 },
    { id: 166, subject: "Кредитование", teacher_id: 12 },
    { id: 167, subject: "Управленческий учет", teacher_id: 34 },
    { id: 168, subject: "Производственный менеджмент", teacher_id: 24 },
    { id: 169, subject: "Бизнес-планирование", teacher_id: 43 },
    { id: 170, subject: "Планирование карьеры", teacher_id: 4 },
    { id: 171, subject: "Мотивация персонала", teacher_id: 27 },
    { id: 172, subject: "Управление проектами", teacher_id: 36 },
    { id: 173, subject: "Делопроизводство", teacher_id: 47 },
    { id: 174, subject: "Работа с кадрами", teacher_id: 35 },
    { id: 175, subject: "Организационное поведение", teacher_id: 26 },
    { id: 176, subject: "Коммуникационный менеджмент", teacher_id: 11 },
    { id: 177, subject: "Внешняя политика", teacher_id: 19 },
    { id: 178, subject: "Историография", teacher_id: 18 },
    { id: 179, subject: "Методология исследований", teacher_id: 41 },
    { id: 180, subject: "Практикум исторических дисциплин", teacher_id: 30 },
    { id: 181, subject: "Историческая география", teacher_id: 49 },
    { id: 182, subject: "Современная историография", teacher_id: 42 },
    { id: 183, subject: "Историческая демография", teacher_id: 32 },
    { id: 184, subject: "Историческая статистика", teacher_id: 20 },
    { id: 185, subject: "Историческая антропология", teacher_id: 16 },
    { id: 186, subject: "Историческая экология", teacher_id: 37 },
    { id: 187, subject: "Этнопсихология", teacher_id: 25 },
    { id: 188, subject: "Социальная философия", teacher_id: 39 },
    { id: 189, subject: "Политическая социология", teacher_id: 10 },
    { id: 190, subject: "История философии", teacher_id: 28 },
    { id: 191, subject: "Философия права", teacher_id: 48 },
    { id: 192, subject: "Научная этика", teacher_id: 3 },
    { id: 193, subject: "Эстетика", учитель_id: 40 },
    { id: 194, subject: "История культуры", teacher_id: 9 },
    { id: 195, subject: "Театр и кино", teacher_id: 21 },
    { id: 196, subject: "Графический дизайн", teacher_id: 6 },
    { id: 197, subject: "Ландшафтный дизайн", teacher_id: 46 },
    { id: 198, subject: "Моделирование одежды", teacher_id: 15 },
    { id: 199, subject: "Техническое рисование", teacher_id: 33 },
    { id: 200, subject: "Рисунок и живопись", teacher_id: 22 }
];

const teachers = [
    { id: 1, teacher: "Иванов Иван Иванович" },
    { id: 2, teacher: "Петрова Анна Сергеевна" },
    { id: 3, teacher: "Смирнов Алексей Дмитриевич" },
    { id: 4, teacher: "Васильева Мария Петровна" },
    { id: 5, teacher: "Попова Елена Владимировна" },
    { id: 6, teacher: "Кузнецов Олег Николаевич" },
    { id: 7, teacher: "Волков Михаил Александрович" },
    { id: 8, teacher: "Семёнова Татьяна Юрьевна" },
    { id: 9, teacher: "Николаева Ольга Игоревна" },
    { id: 10, teacher: "Орлов Дмитрий Сергеевич" },
    { id: 11, teacher: "Зайцева Ирина Алексеевна" },
    { id: 12, teacher: "Леонова Юлия Борисовна" },
    { id: 13, teacher: "Антонов Роман Евгеньевич" },
    { id: 14, teacher: "Голубева Наталья Викторовна" },
    { id: 15, teacher: "Дмитриев Евгений Владимирович" },
    { id: 16, teacher: "Егорова Вера Павловна" },
    { id: 17, teacher: "Казаков Павел Константинович" },
    { id: 18, teacher: "Миронова Светлана Леонидовна" },
    { id: 19, teacher: "Новикова Алина Романовна" },
    { id: 20, teacher: "Павлова Людмила Александровна" },
    { id: 21, teacher: "Романова Дарья Николаевна" },
    { id: 22, teacher: "Сергеев Константин Михайлович" },
    { id: 23, teacher: "Федорова Полина Ивановна" },
    { id: 24, teacher: "Чернова Лариса Дмитриевна" },
    { id: 25, teacher: "Шаров Александр Геннадьевич" },
    { id: 26, teacher: "Белкина Виктория Анатольевна" },
    { id: 27, teacher: "Борисов Денис Валерьевич" },
    { id: 28, teacher: "Горшкова Галина Михайловна" },
    { id: 29, teacher: "Дементьев Пётр Алексеевич" },
    { id: 30, teacher: "Ермолаева Любовь Витальевна" },
    { id: 31, teacher: "Жуков Григорий Дмитриевич" },
    { id: 32, teacher: "Заболотская Анастасия Семёновна" },
    { id: 33, teacher: "Игнатьева София Ильинична" },
    { id: 34, teacher: "Карпов Владислав Георгиевич" },
    { id: 35, teacher: "Колесникова Оксана Фёдоровна" },
    { id: 36, teacher: "Корнеев Максим Валентинович" },
    { id: 37, teacher: "Котова Алла Николаевна" },
    { id: 38, teacher: "Логинова Ульяна Сергеевна" },
    { id: 39, teacher: "Макарова Инна Викторовна" },
    { id: 40, teacher: "Нестеров Юрий Андреевич" },
    { id: 41, teacher: "Осипова Вероника Эдуардовна" },
    { id: 42, teacher: "Перфильева Марина Васильевна" },
    { id: 43, teacher: "Прохоров Илья Павлович" },
    { id: 44, teacher: "Радченко Надежда Аркадьевна" },
    { id: 45, teacher: "Рыбкин Валерий Борисович" },
    { id: 46, teacher: "Салимова Айгуль Рафаэльевна" },
    { id: 47, teacher: "Самойлов Николай Григорьевич" },
    { id: 48, teacher: "Степанова Кристина Станиславовна" },
    { id: 49, teacher: "Суслов Леонид Александрович" },
    { id: 50, teacher: "Тихонова Ольга Сергеевна" }
];

const sub_stud = [
    { id: 1, group_id: 1, subject_id: 178 },
    { id: 2, group_id: 2, subject_id: 42 },
    { id: 3, group_id: 3, subject_id: 126 },
    { id: 4, group_id: 1, subject_id: 33 },
    { id: 5, group_id: 2, subject_id: 164 },
    { id: 6, group_id: 3, subject_id: 89 },
    { id: 7, group_id: 1, subject_id: 143 },
    { id: 8, group_id: 2, subject_id: 107 },
    { id: 9, group_id: 3, subject_id: 197 },
    { id: 10, group_id: 1, subject_id: 11 },
    { id: 11, group_id: 2, subject_id: 136 },
    { id: 12, group_id: 3, subject_id: 63 },
    { id: 13, group_id: 1, subject_id: 189 },
    { id: 14, group_id: 2, subject_id: 154 },
    { id: 15, group_id: 3, subject_id: 168 },
    { id: 16, group_id: 1, subject_id: 72 },
    { id: 17, group_id: 2, subject_id: 121 },
    { id: 18, group_id: 3, subject_id: 103 },
    { id: 19, group_id: 1, subject_id: 59 },
    { id: 20, group_id: 2, subject_id: 84 },
    { id: 21, group_id: 3, subject_id: 194 },
    { id: 22, group_id: 1, subject_id: 37 },
    { id: 23, group_id: 2, subject_id: 171 },
    { id: 24, group_id: 3, subject_id: 139 },
    { id: 25, group_id: 1, subject_id: 113 },
    { id: 26, group_id: 2, subject_id: 96 },
    { id: 27, group_id: 3, subject_id: 45 },
    { id: 28, group_id: 1, subject_id: 148 },
    { id: 29, group_id: 2, subject_id: 185 },
    { id: 30, group_id: 3, subject_id: 69 },
    { id: 31, group_id: 1, subject_id: 200 },
    { id: 32, group_id: 2, subject_id: 158 },
    { id: 33, group_id: 3, subject_id: 119 },
    { id: 34, group_id: 1, subject_id: 133 },
    { id: 35, group_id: 2, subject_id: 77 },
    { id: 36, group_id: 3, subject_id: 163 },
    { id: 37, group_id: 1, subject_id: 105 },
    { id: 38, group_id: 2, subject_id: 51 },
    { id: 39, group_id: 3, subject_id: 174 },
    { id: 40, group_id: 1, subject_id: 87 },
    { id: 41, group_id: 2, subject_id: 146 },
    { id: 42, group_id: 3, subject_id: 190 },
    { id: 43, group_id: 1, subject_id: 124 },
    { id: 44, group_id: 2, subject_id: 66 },
    { id: 45, group_id: 3, subject_id: 182 },
    { id: 46, group_id: 1, subject_id: 151 },
    { id: 47, group_id: 2, subject_id: 39 },
    { id: 48, group_id: 3, subject_id: 116 },
    { id: 49, group_id: 1, subject_id: 93 },
    { id: 50, group_id: 2, subject_id: 169 },
    { id: 51, group_id: 3, subject_id: 74 },
    { id: 52, group_id: 1, subject_id: 131 },
    { id: 53, group_id: 2, subject_id: 48 },
    { id: 54, group_id: 3, subject_id: 196 },
    { id: 55, group_id: 1, subject_id: 101 },
    { id: 56, group_id: 2, subject_id: 61 },
    { id: 57, group_id: 3, subject_id: 177 },
    { id: 58, group_id: 1, subject_id: 141 },
    { id: 59, group_id: 2, subject_id: 82 },
    { id: 60, group_id: 3, subject_id: 157 },
    { id: 61, group_id: 1, subject_id: 31 },
    { id: 62, group_id: 2, subject_id: 129 },
    { id: 63, group_id: 3, subject_id: 187 },
    { id: 64, group_id: 1, subject_id: 99 },
    { id: 65, group_id: 2, subject_id: 161 },
    { id: 66, group_id: 3, subject_id: 70 },
    { id: 67, group_id: 1, subject_id: 134 },
    { id: 68, group_id: 2, subject_id: 56 },
    { id: 69, group_id: 3, subject_id: 193 },
    { id: 70, group_id: 1, subject_id: 109 },
    { id: 71, group_id: 2, subject_id: 64 },
    { id: 72, group_id: 3, subject_id: 173 },
    { id: 73, group_id: 1, subject_id: 145 },
    { id: 74, group_id: 2, subject_id: 86 },
    { id: 75, group_id: 3, subject_id: 160 },
    { id: 76, group_id: 1, subject_id: 35 },
    { id: 77, group_id: 2, subject_id: 130 },
    { id: 78, group_id: 3, subject_id: 184 },
    { id: 79, group_id: 1, subject_id: 104 },
    { id: 80, group_id: 2, subject_id: 54 },
    { id: 81, group_id: 3, subject_id: 192 },
    { id: 82, group_id: 1, subject_id: 153 },
    { id: 83, group_id: 2, subject_id: 76 },
    { id: 84, group_id: 3, subject_id: 170 },
    { id: 85, group_id: 1, subject_id: 41 },
    { id: 86, group_id: 2, subject_id: 127 },
    { id: 87, group_id: 3, subject_id: 181 },
    { id: 88, group_id: 1, subject_id: 98 },
    { id: 89, group_id: 2, subject_id: 166 },
    { id: 90, group_id: 3, subject_id: 67 },
    { id: 91, group_id: 1, subject_id: 137 },
    { id: 92, group_id: 2, subject_id: 52 },
    { id: 93, group_id: 3, subject_id: 195 },
    { id: 94, group_id: 1, subject_id: 111 },
    { id: 95, group_id: 2, subject_id: 79 },
    { id: 96, group_id: 3, subject_id: 176 },
    { id: 97, group_id: 1, subject_id: 149 },
    { id: 98, group_id: 2, subject_id: 91 },
    { id: 99, group_id: 3, subject_id: 165 },
    { id: 100, group_id: 1, subject_id: 38 },
    { id: 101, group_id: 2, subject_id: 125 },
    { id: 102, group_id: 3, subject_id: 186 },
    { id: 103, group_id: 1, subject_id: 106 },
    { id: 104, group_id: 2, subject_id: 60 },
    { id: 105, group_id: 3, subject_id: 191 },
    { id: 106, group_id: 1, subject_id: 156 },
    { id: 107, group_id: 2, subject_id: 73 },
    { id: 108, group_id: 3, subject_id: 172 },
    { id: 109, group_id: 1, subject_id: 40 },
    { id: 110, group_id: 2, subject_id: 132 },
    { id: 111, group_id: 3, subject_id: 183 },
    { id: 112, group_id: 1, subject_id: 102 },
    { id: 113, group_id: 2, subject_id: 57 },
    { id: 114, group_id: 3, subject_id: 199 },
    { id: 115, group_id: 1, subject_id: 150 },
    { id: 116, group_id: 2, subject_id: 75 },
    { id: 117, group_id: 3, subject_id: 175 },
    { id: 118, group_id: 1, subject_id: 36 },
    { id: 119, group_id: 2, subject_id: 128 },
    { id: 120, group_id: 3, subject_id: 188 },
    { id: 121, group_id: 1, subject_id: 108 },
    { id: 122, group_id: 2, subject_id: 62 },
    { id: 123, group_id: 3, subject_id: 198 },
    { id: 124, group_id: 1, subject_id: 155 },
    { id: 125, group_id: 2, subject_id: 81 },
    { id: 126, group_id: 3, subject_id: 179 },
    { id: 127, group_id: 1, subject_id: 44 },
    { id: 128, group_id: 2, subject_id: 135 },
    { id: 129, group_id: 3, subject_id: 180 },
    { id: 130, group_id: 1, subject_id: 110 },
    { id: 131, group_id: 2, subject_id: 55 },
    { id: 132, group_id: 3, subject_id: 19 },
    { id: 133, group_id: 1, subject_id: 159 },
    { id: 134, group_id: 2, subject_id: 80 },
    { id: 135, group_id: 3, subject_id: 167 },
    { id: 136, group_id: 1, subject_id: 47 },
    { id: 137, group_id: 2, subject_id: 123 },
    { id: 138, group_id: 3, subject_id: 18 },
    { id: 139, group_id: 1, subject_id: 115 },
    { id: 140, group_id: 2, subject_id: 65 },
    { id: 141, group_id: 3, subject_id: 17 },
    { id: 142, group_id: 1, subject_id: 152 },
    { id: 143, group_id: 2, subject_id: 78 },
    { id: 144, group_id: 3, subject_id: 162 },
    { id: 145, group_id: 1, subject_id: 46 },
    { id: 146, group_id: 2, subject_id: 138 },
    { id: 147, group_id: 3, subject_id: 20 },
    { id: 148, group_id: 1, subject_id: 114 },
    { id: 149, group_id: 2, subject_id: 58 },
    { id: 150, group_id: 3, subject_id: 16 },
    { id: 151, group_id: 1, subject_id: 147 },
    { id: 152, group_id: 2, subject_id: 95 },
    { id: 153, group_id: 3, subject_id: 17},
    { id: 154, group_id: 1, subject_id: 34 },
    { id: 155, group_id: 2, subject_id: 122 },
    { id: 156, group_id: 3, subject_id: 185 },
    { id: 157, group_id: 1, subject_id: 100 },
    { id: 158, group_id: 2, subject_id: 53 },
    { id: 159, group_id: 3, subject_id: 190 },
    { id: 160, group_id: 1, subject_id: 144 },
    { id: 161, group_id: 2, subject_id: 90 },
    { id: 162, group_id: 3, subject_id: 163 },
    { id: 163, group_id: 1, subject_id: 43 },
    { id: 164, group_id: 2, subject_id: 120 },
    { id: 165, group_id: 3, subject_id: 189 },
    { id: 166, group_id: 1, subject_id: 112 },
    { id: 167, group_id: 2, subject_id: 68 },
    { id: 168, group_id: 3, subject_id: 194 },
    { id: 169, group_id: 1, subject_id: 142 },
    { id: 170, group_id: 2, subject_id: 88 },
    { id: 171, group_id: 3, subject_id: 155 },
    { id: 172, group_id: 1, subject_id: 32 },
    { id: 173, group_id: 2, subject_id: 13 },
    { id: 174, group_id: 3, subject_id: 196 },
    { id: 175, group_id: 1, subject_id: 103 },
    { id: 176, group_id: 2, subject_id: 71 },
    { id: 177, group_id: 3, subject_id: 171 },
    { id: 178, group_id: 1, subject_id: 140 },
    { id: 179, group_id: 2, subject_id: 94 },
    { id: 180, group_id: 3, subject_id: 169 },
    { id: 181, group_id: 1, subject_id: 49 },
    { id: 182, group_id: 2, subject_id: 118 },
    { id: 183, group_id: 3, subject_id: 187 },
    { id: 184, group_id: 1, subject_id: 117 },
    { id: 185, group_id: 2, subject_id: 69 },
    { id: 186, group_id: 3, subject_id: 193 },
    { id: 187, group_id: 1, subject_id: 158 },
    { id: 188, group_id: 2, subject_id: 85 },
    { id: 189, group_id: 3, subject_id: 170 },
    { id: 190, group_id: 1, subject_id: 50 },
    { id: 191, group_id: 2, subject_id: 12 },
    { id: 192, group_id: 3, subject_id: 197 },
    { id: 193, group_id: 1, subject_id: 161 },
    { id: 194, group_id: 2, subject_id: 97 },
    { id: 195, group_id: 3, subject_id: 166 },
    { id: 196, group_id: 1, subject_id: 45 },
    { id: 197, group_id: 2, subject_id: 116 },
    { id: 198, group_id: 3, subject_id: 186 },
    { id: 199, group_id: 1, subject_id: 14 },
    { id: 200, group_id: 2, subject_id: 131 },
    { id: 201, group_id: 3, subject_id: 182 },
    { id: 202, group_id: 1, subject_id: 105 },
    { id: 203, group_id: 2, subject_id: 72 },
    { id: 204, group_id: 3, subject_id: 173 },
    { id: 205, group_id: 1, subject_id: 146 },
    { id: 206, group_id: 2, subject_id: 92 },
    { id: 207, group_id: 3, subject_id: 164 },
    { id: 208, group_id: 1, subject_id: 42 },
    { id: 209, group_id: 2, subject_id: 119 },
    { id: 210, group_id: 3, subject_id: 184 },
    { id: 211, group_id: 1, subject_id: 157 },
    { id: 212, group_id: 2, subject_id: 83 },
    { id: 213, group_id: 3, subject_id: 176 },
    { id: 214, group_id: 1, subject_id: 30 },
    { id: 215, group_id: 2, subject_id: 124 },
    { id: 216, group_id: 3, subject_id: 181 },
    { id: 217, group_id: 1, subject_id: 109 },
    { id: 218, group_id: 2, subject_id: 67 },
    { id: 219, group_id: 3, subject_id: 195 },
    { id: 220, group_id: 1, subject_id: 148 },
    { id: 221, group_id: 2, subject_id: 96 },
    { id: 222, group_id: 3, subject_id: 165 },
    { id: 223, group_id: 1, subject_id: 39 },
    { id: 224, group_id: 2, subject_id: 113 },
    { id: 225, group_id: 3, subject_id: 180 },
    { id: 226, group_id: 1, subject_id: 153 },
    { id: 227, group_id: 2, subject_id: 80 },
    { id: 228, group_id: 3, subject_id: 168 },
    { id: 229, group_id: 1, subject_id: 41 },
    { id: 230, group_id: 2, subject_id: 121 },
    { id: 231, group_id: 3, subject_id: 183 },
    { id: 232, group_id: 1, subject_id: 110 },
    { id: 233, group_id: 2, subject_id: 70 },
    { id: 234, group_id: 3, subject_id: 198 },
    { id: 235, group_id: 1, subject_id: 145 },
    { id: 236, group_id: 2, subject_id: 99 },
    { id: 237, group_id: 3, subject_id: 167 },
    { id: 238, group_id: 1, subject_id: 38 },
    { id: 239, group_id: 2, subject_id: 117 },
    { id: 240, group_id: 3, subject_id: 186 },
    { id: 241, group_id: 1, subject_id: 156 },
    { id: 242, group_id: 2, subject_id: 87 },
    { id: 243, group_id: 3, subject_id: 172 },
    { id: 244, group_id: 1, subject_id: 40 },
    { id: 245, group_id: 2, subject_id: 126 },
    { id: 246, group_id: 3, subject_id: 189 },
    { id: 247, group_id: 1, subject_id: 107 },
    { id: 248, group_id: 2, subject_id: 75 },
    { id: 249, group_id: 3, subject_id: 194 },
    { id: 250, group_id: 1, subject_id: 143 },
    { id: 251, group_id: 2, subject_id: 93 },
    { id: 252, group_id: 3, subject_id: 162 },
    { id: 253, group_id: 1, subject_id: 37 },
    { id: 254, group_id: 2, subject_id: 115 },
    { id: 255, group_id: 3, subject_id: 185 },
    { id: 256, group_id: 1, subject_id: 152 },
    { id: 257, group_id: 2, subject_id: 86 },
    { id: 258, group_id: 3, subject_id: 174 },
    { id: 259, group_id: 1, subject_id: 46 },
    { id: 260, group_id: 2, subject_id: 129 },
    { id: 261, group_id: 3, subject_id: 188 },
    { id: 262, group_id: 1, subject_id: 114 },
    { id: 263, group_id: 2, subject_id: 74 },
    { id: 264, group_id: 3, subject_id: 191 },
    { id: 265, group_id: 1, subject_id: 141 },
    { id: 266, group_id: 2, subject_id: 98 },
    { id: 267, group_id: 3, subject_id: 160 },
    { id: 268, group_id: 1, subject_id: 35 },
    { id: 269, group_id: 2, subject_id: 112 },
    { id: 270, group_id: 3, subject_id: 187 },
    { id: 271, group_id: 1, subject_id: 159 },
    { id: 272, group_id: 2, subject_id: 89 },
    { id: 273, group_id: 3, subject_id: 175 },
    { id: 274, group_id: 1, subject_id: 48 },
    { id: 275, group_id: 2, subject_id: 134 },
    { id: 276, group_id: 3, subject_id: 190 },
    { id: 277, group_id: 1, subject_id: 101 },
    { id: 278, group_id: 2, subject_id: 71 },
    { id: 279, group_id: 3, subject_id: 179 },
    { id: 280, group_id: 1, subject_id: 147 },
    { id: 281, group_id: 2, subject_id: 91 },
    { id: 282, group_id: 3, subject_id: 163 },
    { id: 283, group_id: 1, subject_id: 33 },
    { id: 284, group_id: 2, subject_id: 120 },
    { id: 285, group_id: 3, subject_id: 184 },
    { id: 286, group_id: 1, subject_id: 111 },
    { id: 287, group_id: 2, subject_id: 66 },
    { id: 288, group_id: 3, subject_id: 196 },
    { id: 289, group_id: 1, subject_id: 155 },
    { id: 290, group_id: 2, subject_id: 84 },
    { id: 291, group_id: 3, subject_id: 177 },
    { id: 292, group_id: 1, subject_id: 44 },
    { id: 293, group_id: 2, subject_id: 137 },
    { id: 294, group_id: 3, subject_id: 181 },
    { id: 295, group_id: 1, subject_id: 103 },
    { id: 296, group_id: 2, subject_id: 73 },
    { id: 297, group_id: 3, subject_id: 192 },
    { id: 298, group_id: 1, subject_id: 149 },
    { id: 299, group_id: 2, subject_id: 95 },
    { id: 300, group_id: 3, subject_id: 166 },
    { id: 301, group_id: 1, subject_id: 31 },
    { id: 302, group_id: 2, subject_id: 118 },
    { id: 303, group_id: 3, subject_id: 180 },
    { id: 304, group_id: 1, subject_id: 151 },
    { id: 305, group_id: 2, subject_id: 82 },
    { id: 306, group_id: 3, subject_id: 169 },
    { id: 307, group_id: 1, subject_id: 43 },
    { id: 308, group_id: 2, subject_id: 125 },
    { id: 309, group_id: 3, subject_id: 183 },
    { id: 310, group_id: 1, subject_id: 106 },
    { id: 311, group_id: 2, subject_id: 76 },
    { id: 312, group_id: 3, subject_id: 170 },
    { id: 313, group_id: 1, subject_id: 142 },
    { id: 314, group_id: 2, subject_id: 90 },
    { id: 315, group_id: 3, subject_id: 161 },
    { id: 316, group_id: 1, subject_id: 36 },
    { id: 317, group_id: 2, subject_id: 116 },
    { id: 318, group_id: 3, subject_id: 182 },
    { id: 319, group_id: 1, subject_id: 158 },
    { id: 320, group_id: 2, subject_id: 81 },
    { id: 321, group_id: 3, subject_id: 176 },
    { id: 322, group_id: 1, subject_id: 47 },
    { id: 323, group_id: 2, subject_id: 123 },
    { id: 324, group_id: 3, subject_id: 189 },
    { id: 325, group_id: 1, subject_id: 104 },
    { id: 326, group_id: 2, subject_id: 69 },
    { id: 327, group_id: 3, subject_id: 197 },
    { id: 328, group_id: 1, subject_id: 140 },
    { id: 329, group_id: 2, subject_id: 94 },
    { id: 330, group_id: 3, subject_id: 165 },
    { id: 331, group_id: 1, subject_id: 32 },
    { id: 332, group_id: 2, subject_id: 114 },
    { id: 333, group_id: 3, subject_id: 188 },
    { id: 334, group_id: 1, subject_id: 154 },
    { id: 335, group_id: 2, subject_id: 85 },
    { id: 336, group_id: 3, subject_id: 173 },
    { id: 337, group_id: 1, subject_id: 49 },
    { id: 338, group_id: 2, subject_id: 128 },
    { id: 339, group_id: 3, subject_id: 193 },
    { id: 340, group_id: 1, subject_id: 102 },
    { id: 341, group_id: 2, subject_id: 79 },
    { id: 342, group_id: 3, subject_id: 178 },
    { id: 343, group_id: 1, subject_id: 146 },
    { id: 344, group_id: 2, subject_id: 97 },
    { id: 345, group_id: 3, subject_id: 164 },
    { id: 346, group_id: 1, subject_id: 30 },
    { id: 347, group_id: 2, subject_id: 113 },
    { id: 348, group_id: 3, subject_id: 186 },
    { id: 349, group_id: 1, subject_id: 157 },
    { id: 350, group_id: 2, subject_id: 88 },
    { id: 351, group_id: 3, subject_id: 171 },
    { id: 352, group_id: 1, subject_id: 45 },
    { id: 353, group_id: 2, subject_id: 130 },
    { id: 354, group_id: 3, subject_id: 195 },
    { id: 355, group_id: 1, subject_id: 109 },
    { id: 356, group_id: 2, subject_id: 70 },
    { id: 357, group_id: 3, subject_id: 176 },
    { id: 358, group_id: 1, subject_id: 144 },
    { id: 359, group_id: 2, subject_id: 92 },
    { id: 360, group_id: 3, subject_id: 168 },
    { id: 361, group_id: 1, subject_id: 39 },
    { id: 362, group_id: 2, subject_id: 122 },
    { id: 363, group_id: 3, subject_id: 187 },
    { id: 364, group_id: 1, subject_id: 110 },
    { id: 365, group_id: 2, subject_id: 65 },
    { id: 366, group_id: 3, subject_id: 191 },
    { id: 367, group_id: 1, subject_id: 153 },
    { id: 368, group_id: 2, subject_id: 83 },
    { id: 369, group_id: 3, subject_id: 174 },
    { id: 370, group_id: 1, subject_id: 41 },
    { id: 371, group_id: 2, subject_id: 133 },
    { id: 372, group_id: 3, subject_id: 185 },
    { id: 373, group_id: 1, subject_id: 107 },
    { id: 374, group_id: 2, subject_id: 78 },
    { id: 375, group_id: 3, subject_id: 193 },
    { id: 376, group_id: 1, subject_id: 148 },
    { id: 377, group_id: 2, subject_id: 96 },
    { id: 378, group_id: 3, subject_id: 167 },
    { id: 379, group_id: 1, subject_id: 38 },
    { id: 380, group_id: 2, subject_id: 117 },
    { id: 381, group_id: 3, subject_id: 186 },
    { id: 382, group_id: 1, subject_id: 156 },
    { id: 383, group_id: 2, subject_id: 87 },
    { id: 384, group_id: 3, subject_id: 172 },
    { id: 385, group_id: 1, subject_id: 40 },
    { id: 386, group_id: 2, subject_id: 126 },
    { id: 387, group_id: 3, subject_id: 189 },
    { id: 388, group_id: 1, subject_id: 101 },
    { id: 389, group_id: 2, subject_id: 75 },
    { id: 390, group_id: 3, subject_id: 194 },
    { id: 391, group_id: 1, subject_id: 143 },
    { id: 392, group_id: 2, subject_id: 93 },
    { id: 393, group_id: 3, subject_id: 162 },
    { id: 394, group_id: 1, subject_id: 37 },
    { id: 395, group_id: 2, subject_id: 115 },
    { id: 396, group_id: 3, subject_id: 185 },
    { id: 397, group_id: 1, subject_id: 152 },
    { id: 398, group_id: 2, subject_id: 86 },
    { id: 399, group_id: 3, subject_id: 174 },
    { id: 400, group_id: 1, subject_id: 46 },
    { id: 401, group_id: 2, subject_id: 129 },
    { id: 402, group_id: 3, subject_id: 188 },
    { id: 403, group_id: 1, subject_id: 114 },
    { id: 404, group_id: 2, subject_id: 74 },
    { id: 405, group_id: 3, subject_id: 191 },
    { id: 406, group_id: 1, subject_id: 141 },
    { id: 407, group_id: 2, subject_id: 98 },
    { id: 408, group_id: 3, subject_id: 160 },
    { id: 409, group_id: 1, subject_id: 35 },
    { id: 410, group_id: 2, subject_id: 112 },
    { id: 411, group_id: 3, subject_id: 187 },
    { id: 412, group_id: 1, subject_id: 159 },
    { id: 413, group_id: 2, subject_id: 89 },
    { id: 414, group_id: 3, subject_id: 175 },
    { id: 415, group_id: 1, subject_id: 48 },
    { id: 416, group_id: 2, subject_id: 134 },
    { id: 417, group_id: 3, subject_id: 190 },
    { id: 418, group_id: 1, subject_id: 103 },
    { id: 419, group_id: 2, subject_id: 73 },
    { id: 420, group_id: 3, subject_id: 179 },
    { id: 421, group_id: 1, subject_id: 149 },
    { id: 422, group_id: 2, subject_id: 95 },
    { id: 423, group_id: 3, subject_id: 163 },
    { id: 424, group_id: 1, subject_id: 33 },
    { id: 425, group_id: 2, subject_id: 120 },
    { id: 426, group_id: 3, subject_id: 184 },
    { id: 427, group_id: 1, subject_id: 111 },
    { id: 428, group_id: 2, subject_id: 66 },
    { id: 429, group_id: 3, subject_id: 196 },
    { id: 430, group_id: 1, subject_id: 155 },
    { id: 431, group_id: 2, subject_id: 84 },
    { id: 432, group_id: 3, subject_id: 177 },
    { id: 433, group_id: 1, subject_id: 44 },
    { id: 434, group_id: 2, subject_id: 137 },
    { id: 435, group_id: 3, subject_id: 181 },
    { id: 436, group_id: 1, subject_id: 105 },
    { id: 437, group_id: 2, subject_id: 76 },
    { id: 438, group_id: 3, subject_id: 192 },
    { id: 439, group_id: 1, subject_id: 147 },
    { id: 440, group_id: 2, subject_id: 91 },
    { id: 441, group_id: 3, subject_id: 169 },
    { id: 442, group_id: 1, subject_id: 36 },
    { id: 443, group_id: 2, subject_id: 116 },
    { id: 444, group_id: 3, subject_id: 182 },
    { id: 445, group_id: 1, subject_id: 158 },
    { id: 446, group_id: 2, subject_id: 81 },
    { id: 447, group_id: 3, subject_id: 176 },
    { id: 448, group_id: 1, subject_id: 47 },
    { id: 449, group_id: 2, subject_id: 123 },
    { id: 450, group_id: 3, subject_id: 189 },
    { id: 451, group_id: 1, subject_id: 104 },
    { id: 452, group_id: 2, subject_id: 69 },
    { id: 453, group_id: 3, subject_id: 197 },
    { id: 454, group_id: 1, subject_id: 140 },
    { id: 455, group_id: 2, subject_id: 94 },
    { id: 456, group_id: 3, subject_id: 165 },
    { id: 457, group_id: 1, subject_id: 32 },
    { id: 458, group_id: 2, subject_id: 114 },
    { id: 459, group_id: 3, subject_id: 188 },
    { id: 460, group_id: 1, subject_id: 154 },
    { id: 461, group_id: 2, subject_id: 85 },
    { id: 462, group_id: 3, subject_id: 173 },
    { id: 463, group_id: 1, subject_id: 49 },
    { id: 464, group_id: 2, subject_id: 128 },
    { id: 465, group_id: 3, subject_id: 193 },
    { id: 466, group_id: 1, subject_id: 102 },
    { id: 467, group_id: 2, subject_id: 79 },
    { id: 468, group_id: 3, subject_id: 178 },
    { id: 469, group_id: 1, subject_id: 146 },
    { id: 470, group_id: 2, subject_id: 97 },
    { id: 471, group_id: 3, subject_id: 164 },
    { id: 472, group_id: 1, subject_id: 30 },
    { id: 473, group_id: 2, subject_id: 113 },
    { id: 474, group_id: 3, subject_id: 186 },
    { id: 475, group_id: 1, subject_id: 157 },
    { id: 476, group_id: 2, subject_id: 88 },
    { id: 477, group_id: 3, subject_id: 171 },
    { id: 478, group_id: 1, subject_id: 45 },
    { id: 479, group_id: 2, subject_id: 130 },
    { id: 480, group_id: 3, subject_id: 195 },
    { id: 481, group_id: 1, subject_id: 109 },
    { id: 482, group_id: 2, subject_id: 70 },
    { id: 483, group_id: 3, subject_id: 176 },
    { id: 484, group_id: 1, subject_id: 144 },
    { id: 485, group_id: 2, subject_id: 92 },
    { id: 486, group_id: 3, subject_id: 168 },
    { id: 487, group_id: 1, subject_id: 39 },
    { id: 488, group_id: 2, subject_id: 122 },
    { id: 489, group_id: 3, subject_id: 187 },
    { id: 490, group_id: 1, subject_id: 110 },
    { id: 491, group_id: 2, subject_id: 65 },
    { id: 492, group_id: 3, subject_id: 191 },
    { id: 493, group_id: 1, subject_id: 153 },
    { id: 494, group_id: 2, subject_id: 83 },
    { id: 495, group_id: 3, subject_id: 174 },
    { id: 496, group_id: 1, subject_id: 41 },
    { id: 497, group_id: 2, subject_id: 133 },
    { id: 498, group_id: 3, subject_id: 185 },
    { id: 499, group_id: 1, subject_id: 107 },
    { id: 500, group_id: 2, subject_id: 78 }
];

const grades = [
  {
    "id": 1,
    "sub_stud_id": 1,
    "grades": [
      {
        "date": "2025-09-01",
        "students_grades": [
          {"student_id": 1, "grade": "5"},
          {"student_id": 2, "grade": "4"},
          {"student_id": 3, "grade": ""}
        ]
      },
      {
        "date": "2025-09-08",
        "students_grades": [
          {"student_id": 1, "grade": "3"},
          {"student_id": 2, "grade": "5"},
          {"student_id": 3, "grade": ""}
        ]
      },
      {
        "date": "2025-09-15",
        "students_grades": [
          {"student_id": 1, "grade": "4"},
          {"student_id": 2, "grade": ""},
          {"student_id": 3, "grade": "5"}
        ]
      },
      {
        "date": "2025-09-22",
        "students_grades": [
          {"student_id": 1, "grade": "5"},
          {"student_id": 2, "grade": "4"},
          {"student_id": 3, "grade": ""}
        ]
      },
      {
        "date": "2025-09-29",
        "students_grades": [
          {"student_id": 1, "grade": "4"},
          {"student_id": 2, "grade": "5"},
          {"student_id": 3, "grade": ""}
        ]
      },
      {
        "date": "2025-10-06",
        "students_grades": [
          {"student_id": 1, "grade": "5"},
          {"student_id": 2, "grade": ""},
          {"student_id": 3, "grade": "4"}
        ]
      },
      {
        "date": "2025-10-13",
        "students_grades": [
          {"student_id": 1, "grade": "4"},
          {"student_id": 2, "grade": "5"},
          {"student_id": 3, "grade": ""}
        ]
      },
      {
        "date": "2025-10-20",
        "students_grades": [
          {"student_id": 1, "grade": "5"},
          {"student_id": 2, "grade": "4"},
          {"student_id": 3, "grade": ""}
        ]
      },
      {
        "date": "2025-10-27",
        "students_grades": [
          {"student_id": 1, "grade": "4"},
          {"student_id": 2, "grade": "5"},
          {"student_id": 3, "grade": ""}
        ]
      },
      {
        "date": "2025-11-03",
        "students_grades": [
          {"student_id": 1, "grade": "5"},
          {"student_id": 2, "grade": ""},
          {"student_id": 3, "grade": "4"}
        ]
      },
      {
        "date": "2025-11-10",
        "students_grades": [
          {"student_id": 1, "grade": "4"},
          {"student_id": 2, "grade": "5"},
          {"student_id": 3, "grade": ""}
        ]
      },
      {
        "date": "2025-11-17",
        "students_grades": [
          {"student_id": 1, "grade": "5"},
          {"student_id": 2, "grade": "4"},
          {"student_id": 3, "grade": ""}
        ]
      },
      {
        "date": "2025-11-24",
        "students_grades": [
          {"student_id": 1, "grade": "4"},
          {"student_id": 2, "grade": "5"},
          {"student_id": 3, "grade": ""}
        ]
      },
      {
        "date": "2025-12-01",
        "students_grades": [
          {"student_id": 1, "grade": "5"},
          {"student_id": 2, "grade": ""},
          {"student_id": 3, "grade": "4"}
        ]
      },
      {
        "date": "2025-12-08",
        "students_grades": [
          {"student_id": 1, "grade": "4"},
          {"student_id": 2, "grade": "5"},
          {"student_id": 3, "grade": ""}
        ]
      }
    ]
  },
  {
    "id": 2,
    "sub_stud_id": 2,
    "grades": [
      {
        "date": "2025-09-01",
        "students_grades": [
          {"student_id": 4, "grade": "5"},
          {"student_id": 5, "grade": ""}
        ]
      },
      {
        "date": "2025-09-08",
        "students_grades": [
          {"student_id": 4, "grade": "4"},
          {"student_id": 5, "grade": "5"}
        ]
      },
      {
        "date": "2025-09-15",
        "students_grades": [
          {"student_id": 4, "grade": "5"},
          {"student_id": 5, "grade": ""}
        ]
      },
      {
        "date": "2025-09-22",
        "students_grades": [
          {"student_id": 4, "grade": "4"},
          {"student_id": 5, "grade": "5"}
        ]
      },
      {
        "date": "2025-09-29",
        "students_grades": [
          {"student_id": 4, "grade": "5"},
          {"student_id": 5, "grade": ""}
        ]
      },
      {
        "date": "2025-10-06",
        "students_grades": [
          {"student_id": 4, "grade": "4"},
          {"student_id": 5, "grade": "5"}
        ]
      },
      {
        "date": "2025-10-13",
        "students_grades": [
          {"student_id": 4, "grade": "5"},
          {"student_id": 5, "grade": ""}
        ]
      },
      {
        "date": "2025-10-20",
        "students_grades": [
          {"student_id": 4, "grade": "4"},
          {"student_id": 5, "grade": "5"}
        ]
      },
      {
        "date": "2025-10-27",
        "students_grades": [
          {"student_id": 4, "grade": "5"},
          {"student_id": 5, "grade": ""}
        ]
      },
      {
        "date": "2025-11-03",
        "students_grades": [
          {"student_id": 4, "grade": "4"},
          {"student_id": 5, "grade": "5"}
        ]
      },
      {
        "date": "2025-11-10",
        "students_grades": [
          {"student_id": 4, "grade": "5"},
          {"student_id": 5, "grade": ""}
        ]
      },
      {
        "date": "2025-11-17",
        "students_grades": [
          {"student_id": 4, "grade": "4"},
          {"student_id": 5, "grade": "5"}
        ]
      },
      {
        "date": "2025-11-24",
        "students_grades": [
          {"student_id": 4, "grade": "5"},
          {"student_id": 5, "grade": ""}
        ]
      },
      {
        "date": "2025-12-01",
        "students_grades": [
          {"student_id": 4, "grade": "4"},
          {"student_id": 5, "grade": "5"}
        ]
      },
      {
        "date": "2025-12-08",
        "students_grades": [
          {"student_id": 4, "grade": "5"},
          {"student_id": 5, "grade": ""}
        ]
      }
    ]
  },
  {
    "id": 3,
    "sub_stud_id": 3,
    "grades": [
      {
        "date": "2025-09-01",
        "students_grades": [
          {"student_id": 6, "grade": "5"},
          {"student_id": 7, "grade": "4"},
          {"student_id": 8, "grade": "3"},
          {"student_id": 9, "grade": "5"},
          {"student_id": 10, "grade": "4"},
          {"student_id": 11, "grade": "3"},
          {"student_id": 12, "grade": "5"},
          {"student_id": 13, "grade": "4"},
          {"student_id": 14, "grade": "3"},
          {"student_id": 15, "grade": "5"},
          {"student_id": 16, "grade": "4"},
          {"student_id": 17, "grade": "3"},
          {"student_id": 18, "grade": "5"},
          {"student_id": 19, "grade": "4"},
          {"student_id": 20, "grade": "3"},
          {"student_id": 21, "grade": "5"},
          {"student_id": 22, "grade": "4"},
          {"student_id": 23, "grade": "3"},
          {"student_id": 24, "grade": "5"},
          {"student_id": 25, "grade": "4"},
          {"student_id": 26, "grade": "3"},
          {"student_id": 27, "grade": "5"},
          {"student_id": 28, "grade": "4"},
          {"student_id": 29, "grade": "3"},
          {"student_id": 30, "grade": ""}
        ]
      },
      {
        "date": "2025-09-08",
        "students_grades": [
          {"student_id": 6, "grade": "4"},
          {"student_id": 7, "grade": "5"},
          {"student_id": 8, "grade": "4"},
          {"student_id": 9, "grade": "5"},
          {"student_id": 10, "grade": "4"},
          {"student_id": 11, "grade": "5"},
          {"student_id": 12, "grade": "4"},
          {"student_id": 13, "grade": "5"},
          {"student_id": 14, "grade": "4"},
          {"student_id": 15, "grade": "5"},
          {"student_id": 16, "grade": "4"},
          {"student_id": 17, "grade": "5"},
          {"student_id": 18, "grade": "4"},
          {"student_id": 19, "grade": "5"},
          {"student_id": 20, "grade": "4"},
          {"student_id": 21, "grade": "5"},
          {"student_id": 22, "grade": "4"},
          {"student_id": 23, "grade": "5"},
          {"student_id": 24, "grade": "4"},
          {"student_id": 25, "grade": "5"},
          {"student_id": 26, "grade": "4"},
          {"student_id": 27, "grade": "5"},
          {"student_id": 28, "grade": "4"},
          {"student_id": 29, "grade": "5"},
          {"student_id": 30, "grade": ""}
        ]
      },
      {
        "date": "2025-09-15",
        "students_grades": [
          {"student_id": 6, "grade": "5"},
          {"student_id": 7, "grade": "4"},
          {"student_id": 8, "grade": "5"},
          {"student_id": 9, "grade": "4"},
          {"student_id": 10, "grade": "5"},
          {"student_id": 11, "grade": "4"},
          {"student_id": 12, "grade": "5"},
          {"student_id": 13, "grade": "4"},
          {"student_id": 14, "grade": "5"},
          {"student_id": 15, "grade": "4"},
          {"student_id": 16, "grade": "5"},
          {"student_id": 17, "grade": "4"},
          {"student_id": 18, "grade": "5"},
          {"student_id": 19, "grade": "4"},
          {"student_id": 20, "grade": "5"},
          {"student_id": 21, "grade": "4"},
          {"student_id": 22, "grade": "5"},
          {"student_id": 23, "grade": "4"},
          {"student_id": 24, "grade": "5"},
          {"student_id": 25, "grade": "4"},
          {"student_id": 26, "grade": "5"},
          {"student_id": 27, "grade": "4"},
          {"student_id": 28, "grade": "5"},
          {"student_id": 29, "grade": "4"},
          {"student_id": 30, "grade": ""}
        ]
      },
      {
        "date": "2025-09-22",
        "students_grades": [
          {"student_id": 6, "grade": "4"},
          {"student_id": 7, "grade": "5"},
          {"student_id": 8, "grade": "4"},
          {"student_id": 9, "grade": "5"},
          {"student_id": 10, "grade": "4"},
          {"student_id": 11, "grade": "5"},
          {"student_id": 12, "grade": "4"},
          {"student_id": 13, "grade": "5"},
          {"student_id": 14, "grade": "4"},
          {"student_id": 15, "grade": "5"},
          {"student_id": 16, "grade": "4"},
          {"student_id": 17, "grade": "5"},
          {"student_id": 18, "grade": "4"},
          {"student_id": 19, "grade": "5"},
          {"student_id": 20, "grade": "4"},
          {"student_id": 21, "grade": "5"},
          {"student_id": 22, "grade": "4"},
          {"student_id": 23, "grade": "5"},
          {"student_id": 24, "grade": "4"},
          {"student_id": 25, "grade": "5"},
          {"student_id": 26, "grade": "4"},
          {"student_id": 27, "grade": "5"},
          {"student_id": 28, "grade": "4"},
          {"student_id": 29, "grade": "5"},
          {"student_id": 30, "grade": ""}
        ]
      },
      {
        "date": "2025-09-29",
        "students_grades": [
          {"student_id": 6, "grade": "5"},
          {"student_id": 7, "grade": "4"},
          {"student_id": 8, "grade": "5"},
          {"student_id": 9, "grade": "4"},
          {"student_id": 10, "grade": "5"},
          {"student_id": 11, "grade": "4"},
          {"student_id": 12, "grade": "5"},
          {"student_id": 13, "grade": "4"},
          {"student_id": 14, "grade": "5"},
          {"student_id": 15, "grade": "4"},
          {"student_id": 16, "grade": "5"},
          {"student_id": 17, "grade": "4"},
          {"student_id": 18, "grade": "5"},
          {"student_id": 19, "grade": "4"},
          {"student_id": 20, "grade": "5"},
          {"student_id": 21, "grade": "4"},
          {"student_id": 22, "grade": "5"},
          {"student_id": 23, "grade": "4"},
          {"student_id": 24, "grade": "5"},
          {"student_id": 25, "grade": "4"},
          {"student_id": 26, "grade": "5"},
          {"student_id": 27, "grade": "4"},
          {"student_id": 28, "grade": "5"},
          {"student_id": 29, "grade": "4"},
          {"student_id": 30, "grade": ""}
        ]
      },
      {
        "date": "2025-10-06",
        "students_grades": [
          {"student_id": 6, "grade": "4"},
          {"student_id": 7, "grade": "5"},
          {"student_id": 8, "grade": "4"},
          {"student_id": 9, "grade": "5"},
          {"student_id": 10, "grade": "4"},
          {"student_id": 11, "grade": "5"},
          {"student_id": 12, "grade": "4"},
          {"student_id": 13, "grade": "5"},
          {"student_id": 14, "grade": "4"},
          {"student_id": 15, "grade": "5"},
          {"student_id": 16, "grade": "4"},
          {"student_id": 17, "grade": "5"},
          {"student_id": 18, "grade": "4"},
          {"student_id": 19, "grade": "5"},
          {"student_id": 20, "grade": "4"},
          {"student_id": 21, "grade": "5"},
          {"student_id": 22, "grade": "4"},
          {"student_id": 23, "grade": "5"},
          {"student_id": 24, "grade": "4"},
          {"student_id": 25, "grade": "5"},
          {"student_id": 26, "grade": "4"},
          {"student_id": 27, "grade": "5"},
          {"student_id": 28, "grade": "4"},
          {"student_id": 29, "grade": "5"},
          {"student_id": 30, "grade": ""}
        ]
      },
      {
        "date": "2025-10-13",
        "students_grades": [
          {"student_id": 6, "grade": "5"},
          {"student_id": 7, "grade": "4"},
          {"student_id": 8, "grade": "5"},
          {"student_id": 9, "grade": "4"},
          {"student_id": 10, "grade": "5"},
          {"student_id": 11, "grade": "4"},
          {"student_id": 12, "grade": "5"},
          {"student_id": 13, "grade": "4"},
          {"student_id": 14, "grade": "5"},
          {"student_id": 15, "grade": "4"},
          {"student_id": 16, "grade": "5"},
          {"student_id": 17, "grade": "4"},
          {"student_id": 18, "grade": "5"},
          {"student_id": 19, "grade": "4"},
          {"student_id": 20, "grade": "5"},
          {"student_id": 21, "grade": "4"},
          {"student_id": 22, "grade": "5"},
          {"student_id": 23, "grade": "4"},
          {"student_id": 24, "grade": "5"},
          {"student_id": 25, "grade": "4"},
          {"student_id": 26, "grade": "5"},
          {"student_id": 27, "grade": "4"},
          {"student_id": 28, "grade": "5"},
          {"student_id": 29, "grade": "4"},
          {"student_id": 30, "grade": ""}
        ]
      },
      {
        "date": "2025-10-20",
        "students_grades": [
          {"student_id": 6, "grade": "4"},
          {"student_id": 7, "grade": "5"},
          {"student_id": 8, "grade": "4"},
          {"student_id": 9, "grade": "5"},
          {"student_id": 10, "grade": "4"},
          {"student_id": 11, "grade": "5"},
          {"student_id": 12, "grade": "4"},
          {"student_id": 13, "grade": "5"},
          {"student_id": 14, "grade": "4"},
          {"student_id": 15, "grade": "5"},
          {"student_id": 16, "grade": "4"},
          {"student_id": 17, "grade": "5"},
          {"student_id": 18, "grade": "4"},
          {"student_id": 19, "grade": "5"},
          {"student_id": 20, "grade": "4"},
          {"student_id": 21, "grade": "5"},
          {"student_id": 22, "grade": "4"},
          {"student_id": 23, "grade": "5"},
          {"student_id": 24, "grade": "4"},
          {"student_id": 25, "grade": "5"},
          {"student_id": 26, "grade": "4"},
          {"student_id": 27, "grade": "5"},
          {"student_id": 28, "grade": "4"},
          {"student_id": 29, "grade": "5"},
          {"student_id": 30, "grade": ""}
        ]
      },
      {
        "date": "2025-10-27",
        "students_grades": [
          {"student_id": 6, "grade": "5"},
          {"student_id": 7, "grade": "4"},
          {"student_id": 8, "grade": "5"},
          {"student_id": 9, "grade": "4"},
          {"student_id": 10, "grade": "5"},
          {"student_id": 11, "grade": "4"},
          {"student_id": 12, "grade": "5"},
          {"student_id": 13, "grade": "4"},
          {"student_id": 14, "grade": "5"},
          {"student_id": 15, "grade": "4"},
          {"student_id": 16, "grade": "5"},
          {"student_id": 17, "grade": "4"},
          {"student_id": 18, "grade": "5"},
          {"student_id": 19, "grade": "4"},
          {"student_id": 20, "grade": "5"},
          {"student_id": 21, "grade": "4"},
          {"student_id": 22, "grade": "5"},
          {"student_id": 23, "grade": "4"},
          {"student_id": 24, "grade": "5"},
          {"student_id": 25, "grade": "4"},
          {"student_id": 26, "grade": "5"},
          {"student_id": 27, "grade": "4"},
          {"student_id": 28, "grade": "5"},
          {"student_id": 29, "grade": "4"},
          {"student_id": 30, "grade": ""}
        ]
      },
      {
        "date": "2025-11-03",
        "students_grades": [
          {"student_id": 6, "grade": "4"},
          {"student_id": 7, "grade": "5"},
          {"student_id": 8, "grade": "4"},
          {"student_id": 9, "grade": "5"},
          {"student_id": 10, "grade": "4"},
          {"student_id": 11, "grade": "5"},
          {"student_id": 12, "grade": "4"},
          {"student_id": 13, "grade": "5"},
          {"student_id": 14, "grade": "4"},
          {"student_id": 15, "grade": "5"},
          {"student_id": 16, "grade": "4"},
          {"student_id": 17, "grade": "5"},
          {"student_id": 18, "grade": "4"},
          {"student_id": 19, "grade": "5"},
          {"student_id": 20, "grade": "4"},
          {"student_id": 21, "grade": "5"},
          {"student_id": 22, "grade": "4"},
          {"student_id": 23, "grade": "5"},
          {"student_id": 24, "grade": "4"},
          {"student_id": 25, "grade": "5"},
          {"student_id": 26, "grade": "4"},
          {"student_id": 27, "grade": "5"},
          {"student_id": 28, "grade": "4"},
          {"student_id": 29, "grade": "5"},
          {"student_id": 30, "grade": ""}
        ]
      },
      {
        "date": "2025-11-10",
        "students_grades": [
          {"student_id": 6, "grade": "5"},
          {"student_id": 7, "grade": "4"},
          {"student_id": 8, "grade": "5"},
          {"student_id": 9, "grade": "4"},
          {"student_id": 10, "grade": "5"},
          {"student_id": 11, "grade": "4"},
          {"student_id": 12, "grade": "5"},
          {"student_id": 13, "grade": "4"},
          {"student_id": 14, "grade": "5"},
          {"student_id": 15, "grade": "4"},
          {"student_id": 16, "grade": "5"},
          {"student_id": 17, "grade": "4"},
          {"student_id": 18, "grade": "5"},
          {"student_id": 19, "grade": "4"},
          {"student_id": 20, "grade": "5"},
          {"student_id": 21, "grade": "4"},
          {"student_id": 22, "grade": "5"},
          {"student_id": 23, "grade": "4"},
          {"student_id": 24, "grade": "5"},
          {"student_id": 25, "grade": "4"},
          {"student_id": 26, "grade": "5"},
          {"student_id": 27, "grade": "4"},
          {"student_id": 28, "grade": "5"},
          {"student_id": 29, "grade": "4"},
          {"student_id": 30, "grade": ""}
        ]
      },
      {
        "date": "2025-11-17",
        "students_grades": [
          {"student_id": 6, "grade": "4"},
          {"student_id": 7, "grade": "5"},
          {"student_id": 8, "grade": "4"},
          {"student_id": 9, "grade": "5"},
          {"student_id": 10, "grade": "4"},
          {"student_id": 11, "grade": "5"},
          {"student_id": 12, "grade": "4"},
          {"student_id": 13, "grade": "5"},
          {"student_id": 14, "grade": "4"},
          {"student_id": 15, "grade": "5"},
          {"student_id": 16, "grade": "4"},
          {"student_id": 17, "grade": "5"},
          {"student_id": 18, "grade": "4"},
          {"student_id": 19, "grade": "5"},
          {"student_id": 20, "grade": "4"},
          {"student_id": 21, "grade": "5"},
          {"student_id": 22, "grade": "4"},
          {"student_id": 23, "grade": "5"},
          {"student_id": 24, "grade": "4"},
          {"student_id": 25, "grade": "5"},
          {"student_id": 26, "grade": "4"},
          {"student_id": 27, "grade": "5"},
          {"student_id": 28, "grade": "4"},
          {"student_id": 29, "grade": "5"},
          {"student_id": 30, "grade": ""}
        ]
      },
      {
        "date": "2025-11-24",
        "students_grades": [
          {"student_id": 6, "grade": "5"},
          {"student_id": 7, "grade": "4"},
          {"student_id": 8, "grade": "5"},
          {"student_id": 9, "grade": "4"},
          {"student_id": 10, "grade": "5"},
          {"student_id": 11, "grade": "4"},
          {"student_id": 12, "grade": "5"},
          {"student_id": 13, "grade": "4"},
          {"student_id": 14, "grade": "5"},
          {"student_id": 15, "grade": "4"},
          {"student_id": 16, "grade": "5"},
          {"student_id": 17, "grade": "4"},
          {"student_id": 18, "grade": "5"},
          {"student_id": 19, "grade": "4"},
          {"student_id": 20, "grade": "5"},
          {"student_id": 21, "grade": "4"},
          {"student_id": 22, "grade": "5"},
          {"student_id": 23, "grade": "4"},
          {"student_id": 24, "grade": "5"},
          {"student_id": 25, "grade": "4"},
          {"student_id": 26, "grade": "5"},
          {"student_id": 27, "grade": "4"},
          {"student_id": 28, "grade": "5"},
          {"student_id": 29, "grade": "4"},
          {"student_id": 30, "grade": ""}
        ]
      },
      {
        "date": "2025-12-01",
        "students_grades": [
          {"student_id": 6, "grade": "4"},
          {"student_id": 7, "grade": "5"},
          {"student_id": 8, "grade": "4"},
          {"student_id": 9, "grade": "5"},
          {"student_id": 10, "grade": "4"},
          {"student_id": 11, "grade": "5"},
          {"student_id": 12, "grade": "4"},
          {"student_id": 13, "grade": "5"},
          {"student_id": 14, "grade": "4"},
          {"student_id": 15, "grade": "5"},
          {"student_id": 16, "grade": "4"},
          {"student_id": 17, "grade": "5"},
          {"student_id": 18, "grade": "4"},
          {"student_id": 19, "grade": "5"},
          {"student_id": 20, "grade": "4"},
          {"student_id": 21, "grade": "5"},
          {"student_id": 22, "grade": "4"},
          {"student_id": 23, "grade": "5"},
          {"student_id": 24, "grade": "4"},
          {"student_id": 25, "grade": "5"},
          {"student_id": 26, "grade": "4"},
          {"student_id": 27, "grade": "5"},
          {"student_id": 28, "grade": "4"},
          {"student_id": 29, "grade": "5"},
          {"student_id": 30, "grade": ""}
        ]
      },
      {
        "date": "2025-12-08",
        "students_grades": [
          {"student_id": 6, "grade": "5"},
          {"student_id": 7, "grade": "4"},
          {"student_id": 8, "grade": "5"},
          {"student_id": 9, "grade": "4"},
          {"student_id": 10, "grade": "5"},
          {"student_id": 11, "grade": "4"},
          {"student_id": 12, "grade": "5"},
          {"student_id": 13, "grade": "4"},
          {"student_id": 14, "grade": "5"},
          {"student_id": 15, "grade": "4"},
          {"student_id": 16, "grade": "5"},
          {"student_id": 17, "grade": "4"},
          {"student_id": 18, "grade": "5"},
          {"student_id": 19, "grade": "4"},
          {"student_id": 20, "grade": "5"},
          {"student_id": 21, "grade": "4"},
          {"student_id": 22, "grade": "5"},
          {"student_id": 23, "grade": "4"},
          {"student_id": 24, "grade": "5"},
          {"student_id": 25, "grade": "4"},
          {"student_id": 26, "grade": "5"},
          {"student_id": 27, "grade": "4"},
          {"student_id": 28, "grade": "5"},
          {"student_id": 29, "grade": "4"},
          {"student_id": 30, "grade": ""}
        ]
      },
      {
        "date": "2025-12-15",
        "students_grades": [
          {"student_id": 6, "grade": "4"},
          {"student_id": 7, "grade": "5"},
          {"student_id": 8, "grade": "4"},
          {"student_id": 9, "grade": "5"},
          {"student_id": 10, "grade": "4"},
          {"student_id": 11, "grade": "5"},
          {"student_id": 12, "grade": "4"},
          {"student_id": 13, "grade": "5"},
          {"student_id": 14, "grade": "4"},
          {"student_id": 15, "grade": "5"},
          {"student_id": 16, "grade": "4"},
          {"student_id": 17, "grade": "5"},
          {"student_id": 18, "grade": "4"},
          {"student_id": 19, "grade": "5"},
          {"student_id": 20, "grade": "4"},
          {"student_id": 21, "grade": "5"},
          {"student_id": 22, "grade": "4"},
          {"student_id": 23, "grade": "5"},
          {"student_id": 24, "grade": "4"},
          {"student_id": 25, "grade": "5"},
          {"student_id": 26, "grade": "4"},
          {"student_id": 27, "grade": "5"},
          {"student_id": 28, "grade": "4"},
          {"student_id": 29, "grade": "5"},
          {"student_id": 30, "grade": ""}
        ]
      },
      {
        "date": "2026-01-05",
        "students_grades": [
          {"student_id": 6, "grade": "5"},
          {"student_id": 7, "grade": "4"},
          {"student_id": 8, "grade": "5"},
          {"student_id": 9, "grade": "4"},
          {"student_id": 10, "grade": "5"},
          {"student_id": 11, "grade": "4"},
          {"student_id": 12, "grade": "5"},
          {"student_id": 13, "grade": "4"},
          {"student_id": 14, "grade": "5"},
          {"student_id": 15, "grade": "4"},
          {"student_id": 16, "grade": "5"},
          {"student_id": 17, "grade": "4"},
          {"student_id": 18, "grade": "5"},
          {"student_id": 19, "grade": "4"},
          {"student_id": 20, "grade": "5"},
          {"student_id": 21, "grade": "4"},
          {"student_id": 22, "grade": "5"},
          {"student_id": 23, "grade": "4"},
          {"student_id": 24, "grade": "5"},
          {"student_id": 25, "grade": "4"},
          {"student_id": 26, "grade": "5"},
          {"student_id": 27, "grade": "4"},
          {"student_id": 28, "grade": "5"},
          {"student_id": 29, "grade": "4"},
          {"student_id": 30, "grade": ""}
        ]
      },
      {
        "date": "2026-01-12",
        "students_grades": [
          {"student_id": 6, "grade": "4"},
          {"student_id": 7, "grade": "5"},
          {"student_id": 8, "grade": "4"},
          {"student_id": 9, "grade": "5"},
          {"student_id": 10, "grade": "4"},
          {"student_id": 11, "grade": "5"},
          {"student_id": 12, "grade": "4"},
          {"student_id": 13, "grade": "5"},
          {"student_id": 14, "grade": "4"},
          {"student_id": 15, "grade": "5"},
          {"student_id": 16, "grade": "4"},
          {"student_id": 17, "grade": "5"},
          {"student_id": 18, "grade": "4"},
          {"student_id": 19, "grade": "5"},
          {"student_id": 20, "grade": "4"},
          {"student_id": 21, "grade": "5"},
          {"student_id": 22, "grade": "4"},
          {"student_id": 23, "grade": "5"},
          {"student_id": 24, "grade": "4"},
          {"student_id": 25, "grade": "5"},
          {"student_id": 26, "grade": "4"},
          {"student_id": 27, "grade": "5"},
          {"student_id": 28, "grade": "4"},
          {"student_id": 29, "grade": "5"},
          {"student_id": 30, "grade": ""}
        ]
      },
      {
        "date": "2026-01-19",
        "students_grades": [
          {"student_id": 6, "grade": "5"},
          {"student_id": 7, "grade": "4"},
          {"student_id": 8, "grade": "5"},
          {"student_id": 9, "grade": "4"},
          {"student_id": 10, "grade": "5"},
          {"student_id": 11, "grade": "4"},
          {"student_id": 12, "grade": "5"},
          {"student_id": 13, "grade": "4"},
          {"student_id": 14, "grade": "5"},
          {"student_id": 15, "grade": "4"},
          {"student_id": 16, "grade": "5"},
          {"student_id": 17, "grade": "4"},
          {"student_id": 18, "grade": "5"},
          {"student_id": 19, "grade": "4"},
          {"student_id": 20, "grade": "5"},
          {"student_id": 21, "grade": "4"},
          {"student_id": 22, "grade": "5"},
          {"student_id": 23, "grade": "4"},
          {"student_id": 24, "grade": "5"},
          {"student_id": 25, "grade": "4"},
          {"student_id": 26, "grade": "5"},
          {"student_id": 27, "grade": "4"},
          {"student_id": 28, "grade": "5"},
          {"student_id": 29, "grade": "4"},
          {"student_id": 30, "grade": ""}
        ]
      },
      {
        "date": "2026-01-26",
        "students_grades": [
          {"student_id": 6, "grade": "4"},
          {"student_id": 7, "grade": "5"},
          {"student_id": 8, "grade": "4"},
          {"student_id": 9, "grade": "5"},
          {"student_id": 10, "grade": "4"},
          {"student_id": 11, "grade": "5"},
          {"student_id": 12, "grade": "4"},
          {"student_id": 13, "grade": "5"},
          {"student_id": 14, "grade": "4"},
          {"student_id": 15, "grade": "5"},
          {"student_id": 16, "grade": "4"},
          {"student_id": 17, "grade": "5"},
          {"student_id": 18, "grade": "4"},
          {"student_id": 19, "grade": "5"},
          {"student_id": 20, "grade": "4"},
          {"student_id": 21, "grade": "5"},
          {"student_id": 22, "grade": "4"},
          {"student_id": 23, "grade": "5"},
          {"student_id": 24, "grade": "4"},
          {"student_id": 25, "grade": "5"},
          {"student_id": 26, "grade": "4"},
          {"student_id": 27, "grade": "5"},
          {"student_id": 28, "grade": "4"},
          {"student_id": 29, "grade": "5"},
          {"student_id": 30, "grade": ""}
        ]
      },
      {
        "date": "2026-02-02",
        "students_grades": [
          {"student_id": 6, "grade": "5"},
          {"student_id": 7, "grade": "4"},
          {"student_id": 8, "grade": "5"},
          {"student_id": 9, "grade": "4"},
          {"student_id": 10, "grade": "5"},
          {"student_id": 11, "grade": "4"},
          {"student_id": 12, "grade": "5"},
          {"student_id": 13, "grade": "4"},
          {"student_id": 14, "grade": "5"},
          {"student_id": 15, "grade": "4"},
          {"student_id": 16, "grade": "5"},
          {"student_id": 17, "grade": "4"},
          {"student_id": 18, "grade": "5"},
          {"student_id": 19, "grade": "4"},
          {"student_id": 20, "grade": "5"},
          {"student_id": 21, "grade": "4"},
          {"student_id": 22, "grade": "5"},
          {"student_id": 23, "grade": "4"},
          {"student_id": 24, "grade": "5"},
          {"student_id": 25, "grade": "4"},
          {"student_id": 26, "grade": "5"},
          {"student_id": 27, "grade": "4"},
          {"student_id": 28, "grade": "5"},
          {"student_id": 29, "grade": "4"},
          {"student_id": 30, "grade": ""}
        ]
      },
      {
        "date": "2026-02-09",
        "students_grades": [
          {"student_id": 6, "grade": "4"},
          {"student_id": 7, "grade": "5"},
          {"student_id": 8, "grade": "4"},
          {"student_id": 9, "grade": "5"},
          {"student_id": 10, "grade": "4"},
          {"student_id": 11, "grade": "5"},
          {"student_id": 12, "grade": "4"},
          {"student_id": 13, "grade": "5"},
          {"student_id": 14, "grade": "4"},
          {"student_id": 15, "grade": "5"},
          {"student_id": 16, "grade": "4"},
          {"student_id": 17, "grade": "5"},
          {"student_id": 18, "grade": "4"},
          {"student_id": 19, "grade": "5"},
          {"student_id": 20, "grade": "4"},
          {"student_id": 21, "grade": "5"},
          {"student_id": 22, "grade": "4"},
          {"student_id": 23, "grade": "5"},
          {"student_id": 24, "grade": "4"},
          {"student_id": 25, "grade": "5"},
          {"student_id": 26, "grade": "4"},
          {"student_id": 27, "grade": "5"},
          {"student_id": 28, "grade": "4"},
          {"student_id": 29, "grade": "5"},
          {"student_id": 30, "grade": ""}
        ]
      },
      {
        "date": "2026-02-16",
        "students_grades": [
          {"student_id": 6, "grade": "5"},
          {"student_id": 7, "grade": "4"},
          {"student_id": 8, "grade": "5"},
          {"student_id": 9, "grade": "4"},
          {"student_id": 10, "grade": "5"},
          {"student_id": 11, "grade": "4"},
          {"student_id": 12, "grade": "5"},
          {"student_id": 13, "grade": "4"},
          {"student_id": 14, "grade": "5"},
          {"student_id": 15, "grade": "4"},
          {"student_id": 16, "grade": "5"},
          {"student_id": 17, "grade": "4"},
          {"student_id": 18, "grade": "5"},
          {"student_id": 19, "grade": "4"},
          {"student_id": 20, "grade": "5"},
          {"student_id": 21, "grade": "4"},
          {"student_id": 22, "grade": "5"},
          {"student_id": 23, "grade": "4"},
          {"student_id": 24, "grade": "5"},
          {"student_id": 25, "grade": "4"},
          {"student_id": 26, "grade": "5"},
          {"student_id": 27, "grade": "4"},
          {"student_id": 28, "grade": "5"},
          {"student_id": 29, "grade": "4"},
          {"student_id": 30, "grade": ""}
        ]
      },
      {
        "date": "2026-02-23",
        "students_grades": [
          {"student_id": 6, "grade": "4"},
          {"student_id": 7, "grade": "5"},
          {"student_id": 8, "grade": "4"},
          {"student_id": 9, "grade": "5"},
          {"student_id": 10, "grade": "4"},
          {"student_id": 11, "grade": "5"},
          {"student_id": 12, "grade": "4"},
          {"student_id": 13, "grade": "5"},
          {"student_id": 14, "grade": "4"},
          {"student_id": 15, "grade": "5"},
          {"student_id": 16, "grade": "4"},
          {"student_id": 17, "grade": "5"},
          {"student_id": 18, "grade": "4"},
          {"student_id": 19, "grade": "5"},
          {"student_id": 20, "grade": "4"},
          {"student_id": 21, "grade": "5"},
          {"student_id": 22, "grade": "4"},
          {"student_id": 23, "grade": "5"},
          {"student_id": 24, "grade": "4"},
          {"student_id": 25, "grade": "5"},
          {"student_id": 26, "grade": "4"},
          {"student_id": 27, "grade": "5"},
          {"student_id": 28, "grade": "4"},
          {"student_id": 29, "grade": "5"},
          {"student_id": 30, "grade": ""}
        ]
      },
      {
        "date": "2026-03-02",
        "students_grades": [
          {"student_id": 6, "grade": "5"},
          {"student_id": 7, "grade": "4"},
          {"student_id": 8, "grade": "5"},
          {"student_id": 9, "grade": "4"},
          {"student_id": 10, "grade": "5"},
          {"student_id": 11, "grade": "4"},
          {"student_id": 12, "grade": "5"},
          {"student_id": 13, "grade": "4"},
          {"student_id": 14, "grade": "5"},
          {"student_id": 15, "grade": "4"},
          {"student_id": 16, "grade": "5"},
          {"student_id": 17, "grade": "4"},
          {"student_id": 18, "grade": "5"},
          {"student_id": 19, "grade": "4"},
          {"student_id": 20, "grade": "5"},
          {"student_id": 21, "grade": "4"},
          {"student_id": 22, "grade": "5"},
          {"student_id": 23, "grade": "4"},
          {"student_id": 24, "grade": "5"},
          {"student_id": 25, "grade": "4"},
          {"student_id": 26, "grade": "5"},
          {"student_id": 27, "grade": "4"},
          {"student_id": 28, "grade": "5"},
          {"student_id": 29, "grade": "4"},
          {"student_id": 30, "grade": ""}
        ]
      },
      {
        "date": "2026-03-09",
        "students_grades": [
          {"student_id": 6, "grade": "4"},
          {"student_id": 7, "grade": "5"},
          {"student_id": 8, "grade": "4"},
          {"student_id": 9, "grade": "5"},
          {"student_id": 10, "grade": "4"},
          {"student_id": 11, "grade": "5"},
          {"student_id": 12, "grade": "4"},
          {"student_id": 13, "grade": "5"},
          {"student_id": 14, "grade": "4"},
          {"student_id": 15, "grade": "5"},
          {"student_id": 16, "grade": "4"},
          {"student_id": 17, "grade": "5"},
          {"student_id": 18, "grade": "4"},
          {"student_id": 19, "grade": "5"},
          {"student_id": 20, "grade": "4"},
          {"student_id": 21, "grade": "5"},
          {"student_id": 22, "grade": "4"},
          {"student_id": 23, "grade": "5"},
          {"student_id": 24, "grade": "4"},
          {"student_id": 25, "grade": "5"},
          {"student_id": 26, "grade": "4"},
          {"student_id": 27, "grade": "5"},
          {"student_id": 28, "grade": "4"},
          {"student_id": 29, "grade": "5"},
          {"student_id": 30, "grade": ""}
        ]
      },
      {
        "date": "2026-03-16",
        "students_grades": [
          {"student_id": 6, "grade": "5"},
          {"student_id": 7, "grade": "4"},
          {"student_id": 8, "grade": "5"},
          {"student_id": 9, "grade": "4"},
          {"student_id": 10, "grade": "5"},
          {"student_id": 11, "grade": "4"},
          {"student_id": 12, "grade": "5"},
          {"student_id": 13, "grade": "4"},
          {"student_id": 14, "grade": "5"},
          {"student_id": 15, "grade": "4"},
          {"student_id": 16, "grade": "5"},
          {"student_id": 17, "grade": "4"},
          {"student_id": 18, "grade": "5"},
          {"student_id": 19, "grade": "4"},
          {"student_id": 20, "grade": "5"},
          {"student_id": 21, "grade": "4"},
          {"student_id": 22, "grade": "5"},
          {"student_id": 23, "grade": "4"},
          {"student_id": 24, "grade": "5"},
          {"student_id": 25, "grade": "4"},
          {"student_id": 26, "grade": "5"},
          {"student_id": 27, "grade": "4"},
          {"student_id": 28, "grade": "5"},
          {"student_id": 29, "grade": "4"},
          {"student_id": 30, "grade": ""}
        ]
      },
      {
        "date": "2026-03-23",
        "students_grades": [
          {"student_id": 6, "grade": "4"},
          {"student_id": 7, "grade": "5"},
          {"student_id": 8, "grade": "4"},
          {"student_id": 9, "grade": "5"},
          {"student_id": 10, "grade": "4"},
          {"student_id": 11, "grade": "5"},
          {"student_id": 12, "grade": "4"},
          {"student_id": 13, "grade": "5"},
          {"student_id": 14, "grade": "4"},
          {"student_id": 15, "grade": "5"},
          {"student_id": 16, "grade": "4"},
          {"student_id": 17, "grade": "5"},
          {"student_id": 18, "grade": "4"},
          {"student_id": 19, "grade": "5"},
          {"student_id": 20, "grade": "4"},
          {"student_id": 21, "grade": "5"},
          {"student_id": 22, "grade": "4"},
          {"student_id": 23, "grade": "5"},
          {"student_id": 24, "grade": "4"},
          {"student_id": 25, "grade": "5"},
          {"student_id": 26, "grade": "4"},
          {"student_id": 27, "grade": "5"},
          {"student_id": 28, "grade": "4"},
          {"student_id": 29, "grade": "5"},
          {"student_id": 30, "grade": ""}
        ]
      },
      {
        "date": "2026-03-30",
        "students_grades": [
          {"student_id": 6, "grade": "5"},
          {"student_id": 7, "grade": "4"},
          {"student_id": 8, "grade": "5"},
          {"student_id": 9, "grade": "4"},
          {"student_id": 10, "grade": "5"},
          {"student_id": 11, "grade": "4"},
          {"student_id": 12, "grade": "5"},
          {"student_id": 13, "grade": "4"},
          {"student_id": 14, "grade": "5"},
          {"student_id": 15, "grade": "4"},
          {"student_id": 16, "grade": "5"},
          {"student_id": 17, "grade": "4"},
          {"student_id": 18, "grade": "5"},
          {"student_id": 19, "grade": "4"},
          {"student_id": 20, "grade": "5"},
          {"student_id": 21, "grade": "4"},
          {"student_id": 22, "grade": "5"},
          {"student_id": 23, "grade": "4"},
          {"student_id": 24, "grade": "5"},
          {"student_id": 25, "grade": "4"},
          {"student_id": 26, "grade": "5"},
          {"student_id": 27, "grade": "4"},
          {"student_id": 28, "grade": "5"},
          {"student_id": 29, "grade": "4"},
          {"student_id": 30, "grade": ""}
        ]
      },
      {
        "date": "2026-04-06",
        "students_grades": [
          {"student_id": 6, "grade": "4"},
          {"student_id": 7, "grade": "5"},
          {"student_id": 8, "grade": "4"},
          {"student_id": 9, "grade": "5"},
          {"student_id": 10, "grade": "4"},
          {"student_id": 11, "grade": "5"},
          {"student_id": 12, "grade": "4"},
          {"student_id": 13, "grade": "5"},
          {"student_id": 14, "grade": "4"},
          {"student_id": 15, "grade": "5"},
          {"student_id": 16, "grade": "4"},
          {"student_id": 17, "grade": "5"},
          {"student_id": 18, "grade": "4"},
          {"student_id": 19, "grade": "5"},
          {"student_id": 20, "grade": "4"},
          {"student_id": 21, "grade": "5"},
          {"student_id": 22, "grade": "4"},
          {"student_id": 23, "grade": "5"},
          {"student_id": 24, "grade": "4"},
          {"student_id": 25, "grade": "5"},
          {"student_id": 26, "grade": "4"},
          {"student_id": 27, "grade": "5"},
          {"student_id": 28, "grade": "4"},
          {"student_id": 29, "grade": "5"},
          {"student_id": 30, "grade": ""}
        ]
      },
      {
        "date": "2026-04-13",
        "students_grades": [
          {"student_id": 6, "grade": "5"},
          {"student_id": 7, "grade": "4"},
          {"student_id": 8, "grade": "5"},
          {"student_id": 9, "grade": "4"},
          {"student_id": 10, "grade": "5"},
          {"student_id": 11, "grade": "4"},
          {"student_id": 12, "grade": "5"},
          {"student_id": 13, "grade": "4"},
          {"student_id": 14, "grade": "5"},
          {"student_id": 15, "grade": "4"},
          {"student_id": 16, "grade": "5"},
          {"student_id": 17, "grade": "4"},
          {"student_id": 18, "grade": "5"},
          {"student_id": 19, "grade": "4"},
          {"student_id": 20, "grade": "5"},
          {"student_id": 21, "grade": "4"},
          {"student_id": 22, "grade": "5"},
          {"student_id": 23, "grade": "4"},
          {"student_id": 24, "grade": "5"},
          {"student_id": 25, "grade": "4"},
          {"student_id": 26, "grade": "5"},
          {"student_id": 27, "grade": "4"},
          {"student_id": 28, "grade": "5"},
          {"student_id": 29, "grade": "4"},
          {"student_id": 30, "grade": ""}
        ]
      },
      {
        "date": "2026-04-20",
        "students_grades": [
          {"student_id": 6, "grade": "4"},
          {"student_id": 7, "grade": "5"},
          {"student_id": 8, "grade": "4"},
          {"student_id": 9, "grade": "5"},
          {"student_id": 10, "grade": "4"},
          {"student_id": 11, "grade": "5"},
          {"student_id": 12, "grade": "4"},
          {"student_id": 13, "grade": "5"},
          {"student_id": 14, "grade": "4"},
          {"student_id": 15, "grade": "5"},
          {"student_id": 16, "grade": "4"},
          {"student_id": 17, "grade": "5"},
          {"student_id": 18, "grade": "4"},
          {"student_id": 19, "grade": "5"},
          {"student_id": 20, "grade": "4"},
          {"student_id": 21, "grade": "5"},
          {"student_id": 22, "grade": "4"},
          {"student_id": 23, "grade": "5"},
          {"student_id": 24, "grade": "4"},
          {"student_id": 25, "grade": "5"},
          {"student_id": 26, "grade": "4"},
          {"student_id": 27, "grade": "5"},
          {"student_id": 28, "grade": "4"},
          {"student_id": 29, "grade": "5"},
          {"student_id": 30, "grade": ""}
        ]
      },
      {
        "date": "2026-04-27",
        "students_grades": [
          {"student_id": 6, "grade": "5"},
          {"student_id": 7, "grade": "4"},
          {"student_id": 8, "grade": "5"},
          {"student_id": 9, "grade": "4"},
          {"student_id": 10, "grade": "5"},
          {"student_id": 11, "grade": "4"},
          {"student_id": 12, "grade": "5"},
          {"student_id": 13, "grade": "4"},
          {"student_id": 14, "grade": "5"},
          {"student_id": 15, "grade": "4"},
          {"student_id": 16, "grade": "5"},
          {"student_id": 17, "grade": "4"},
          {"student_id": 18, "grade": "5"},
          {"student_id": 19, "grade": "4"},
          {"student_id": 20, "grade": "5"},
          {"student_id": 21, "grade": "4"},
          {"student_id": 22, "grade": "5"},
          {"student_id": 23, "grade": "4"},
          {"student_id": 24, "grade": "5"},
          {"student_id": 25, "grade": "4"},
          {"student_id": 26, "grade": "5"},
          {"student_id": 27, "grade": "4"},
          {"student_id": 28, "grade": "5"},
          {"student_id": 29, "grade": "4"},
          {"student_id": 30, "grade": ""}
        ]
      },
      {
        "date": "2026-05-04",
        "students_grades": [
          {"student_id": 6, "grade": "4"},
          {"student_id": 7, "grade": "5"},
          {"student_id": 8, "grade": "4"},
          {"student_id": 9, "grade": "5"},
          {"student_id": 10, "grade": "4"},
          {"student_id": 11, "grade": "5"},
          {"student_id": 12, "grade": "4"},
          {"student_id": 13, "grade": "5"},
          {"student_id": 14, "grade": "4"},
          {"student_id": 15, "grade": "5"},
          {"student_id": 16, "grade": "4"},
          {"student_id": 17, "grade": "5"},
          {"student_id": 18, "grade": "4"},
          {"student_id": 19, "grade": "5"},
          {"student_id": 20, "grade": "4"},
          {"student_id": 21, "grade": "5"},
          {"student_id": 22, "grade": "4"},
          {"student_id": 23, "grade": "5"},
          {"student_id": 24, "grade": "4"},
          {"student_id": 25, "grade": "5"},
          {"student_id": 26, "grade": "4"},
          {"student_id": 27, "grade": "5"},
          {"student_id": 28, "grade": "4"},
          {"student_id": 29, "grade": "5"},
          {"student_id": 30, "grade": ""}
        ]
      }
    ]
  }
];


// let sub_select = document.querySelector("#subject");
// let group_select = document.querySelector("#group");

// sub_select.innerHTML = `<option value="-" selected disabled>Выберите предмет</option>`;
// group_select.innerHTML = `<option value="-" selected disabled>Выберите группу</option>`;

// const teacher = localStorage.getItem("teacher");
// const teacher_sub = subjects.filter(s => s.teacher_id == teacher);

// for (let ts of teacher_sub) {
//     console.log(ts);
//     let option = document.createElement("option");
//     option.value = ts.id;
//     option.textContent = ts.subject;
//     sub_select.appendChild(option);
// }

// sub_select.addEventListener("change", () => {
//     group_select.innerHTML = `<option value="-" selected disabled>Выберите группу</option>`;

//     console.log(sub_select.value);
//     const sub = sub_stud.filter(ss => ss.subject_id == sub_select.value);
//     for (let s of sub) {
//         let option = document.createElement("option");
//         option.value = s.group_id;
//         option.textContent = groups.find(g => g.id == s.group_id).group;
//         group_select.appendChild(option);
//     }
// });

// group_select.addEventListener("change", () => {
//     const _students = students.filter(st => st.group_id == group_select.value);
//     let table = document.querySelector("#st_tbody");
//     let index = 1;
//     table.innerHTML = "";
//     for (let st of _students) {
//         table.innerHTML += `<tr>
//                                 <td>${index}. </td>
//                                 <td>${st.student}</td>
//                                 <td><input type="text"></td>
//                             </tr>`;
//         index++;
//     }
// });

function openLessonSettings(lesson, group) {
    return `<div class="form" id="lessonSettings">
            <div class="form-header">
                <h2>Редактирование урока</h2>
                <svg width="19px" height="100%" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M18 6L6 18M6 6L18 18" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                        stroke-linejoin="round" />
                </svg>
            </div>
            <p class="form-description">Вы можете создавать новые занятия, а также редактировать существующие</p>
            <div class="form-section">
                <label for="date">Дата занятия</label>
                <input type="date" onchange="{console.log(this.value)}" id="date">
                <br>
                <select class="form-section-select" id="subject"></select>
            </div>
            <div class="form-section">
                <h3>Успеваемость учащихся</h3>
                <select class="form-section-select" id="group"></select>
                <table>
                    <thead>
                        <tr>
                            <th colspan="2">Учащиеся</th>
                            <th>Оценивание</th>
                        </tr>
                    </thead>
                    <tbody id="st_tbody"></tbody>
                </table>
            </div>
            <button class="button primary" onclick="saveThemeSubject()">Создать/Сохранить</button>
        </div>`;
}




function setGroupsList(filter) {
    let group_list = document.querySelector("#groups-list");
    group_list.innerHTML = "";
    const teacher = localStorage.getItem("teacher");
    const subject = subjects.filter(s => s.teacher_id == teacher);
    let _subs = [];

    for (let s of subject) {
        const _s = sub_stud.filter(st => st.subject_id == s.id);
        for (let gr of _s) {
            if (!_subs.includes(gr.group_id)) {
                _subs.push(gr.group_id);
            }
        }
    }

    for (let group of _subs) {
        let btn = document.createElement("button");
        const _group = groups.find(g => g.id == group);
        let filteredGroup = _group.group.trim().toLowerCase().includes(filter.trim().toLowerCase());
        if (filteredGroup) {
            btn.textContent = _group.group;
            btn.addEventListener("click", () => {
                window.location.href = `/src/pages/?group_id=${_group.id}`;
            });
            group_list.appendChild(btn);
        }
    }
}

function setJournalsList(filter) {
    let journal_list = document.querySelector("#journal-list");
    journal_list.innerHTML = "";
    const teacher = localStorage.getItem("teacher");
    const subject = subjects.filter(s => s.teacher_id == teacher);
    let _subs = [];

    for (let s of subject) {
        const _s = sub_stud.filter(st => st.subject_id == s.id);
        for (let gr of _s) {
            _subs.push(gr);
        }
    }

    for (let group of _subs) {
        let btn = document.createElement("button");

        const _subject = subjects.find(s => s.id == group.subject_id);
        const _group = groups.find(g => g.id == group.group_id);

        let filteredGroup = _group.group.trim().toLowerCase().includes(filter.trim().toLowerCase());
        let filteredSubject = _subject.subject.trim().toLowerCase().includes(filter.trim().toLowerCase());
        if (filteredGroup || filteredSubject) {
            btn.textContent = `🕮 ${_subject.subject} ${_group.group}`;
            btn.addEventListener("click", () => {
                window.location.href = `/src/pages/?group_id=${_group.id}&subject_id=${_subject.id}`;
            });
            journal_list.appendChild(btn);
        }
    }
}

setGroupsList("");
setJournalsList("");